### ISSUE TITLE
Destructuring allow renaming

### ISSUE THREAD

**Issue by julien-vidal** [hbourzeix/react-training#2]
https://github.com/hbourzeix/react-training/blob/47f0e88787cb7444e478eefb14d4006d7a39dda2/deck/snippets/objDestructuration.js#L10

You can rename a variable by using the following syntax : 
```
...,
lastName: NomDeFamille
```

`NomDeFamille` will contain lastName

**Comment by github-herve-bourzeix** [comment]
Yeah , merci je ne savais pas

**Comment by github-herve-bourzeix** [comment]
added a slide
